"""Professional PDF report generation for a Kyther scan. Light theme, reportlab.

Report(scan_dict).generate() -> PDF bytes. Only cover_page() is fully built here;
the other sections are structured stubs to fill in against the design spec.
"""
from __future__ import annotations

import hashlib
import io
import json
import re
import textwrap
from datetime import datetime, timezone
from urllib.parse import urlsplit

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    Flowable, HRFlowable, PageBreak, Paragraph, Preformatted, SimpleDocTemplate,
    Spacer, Table, TableStyle,
)

# ── Fonts: use the brand TTFs if bundled, else reportlab defaults ────────────
FONT_TITLE, FONT_BODY, FONT_MONO = "Helvetica-Bold", "Helvetica", "Courier"


def _register_fonts(font_dir="kyther/assets/fonts"):
    global FONT_TITLE, FONT_MONO
    import os
    for face, fname, target in [
        ("Quicksand", "Quicksand-Bold.ttf", "FONT_TITLE"),
        ("JetBrainsMono", "JetBrainsMono-Regular.ttf", "FONT_MONO"),
    ]:
        path = os.path.join(font_dir, fname)
        if os.path.exists(path):
            try:
                pdfmetrics.registerFont(TTFont(face, path))
                globals()[target] = face
            except Exception:
                pass


_register_fonts()

# ── Palette (light-theme-safe) ──────────────────────────────────────────────
PURPLE = colors.HexColor("#7C5BA6")
PURPLE_LT = colors.HexColor("#bfa4e4")
INK = colors.HexColor("#1a1a1a")
MUTED = colors.HexColor("#6B6475")
HAIRLINE = colors.HexColor("#e5e0ec")

CONF_STYLE = {  # level -> (fill, text, glyph)
    "confirmed": (colors.HexColor("#E3F7EC"), colors.HexColor("#128A4E"), "●"),
    "probable": (colors.HexColor("#FBF1DA"), colors.HexColor("#9A6B00"), "◐"),
    "possible": (colors.HexColor("#EDEAF1"), colors.HexColor("#6B6475"), "○"),
}
TIER_COLOR = {
    "Critical": colors.HexColor("#C0392B"), "High": colors.HexColor("#D64545"),
    "Medium": colors.HexColor("#C2A24F"), "Low": colors.HexColor("#2F9E63"),
}
CONF_WEIGHT = {"confirmed": "×1.0", "probable": "×0.6", "possible": "×0.2"}
CONF_ORDER = ["confirmed", "probable", "possible"]
CONF_RANK = {"possible": 0, "probable": 1, "confirmed": 2}
CONF_DESC = {"confirmed": "control-verified", "probable": "corroborated",
             "possible": "status-code only — verify"}
# Semantic hexes for chips/narrative (reportlab Paragraph font color wants a string).
SEM_RED, SEM_AMBER, SEM_GREEN = "#D64545", "#C2A24F", "#2F9E63"


def _hexstr(c) -> str:
    return "#" + c.hexval()[2:]


# Value patterns for appendix redaction.
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
_URL_RE = re.compile(r"^(https?://|[\w.-]+\.[a-z]{2,}(/|$|\?|:))", re.I)

DISCLAIMER = (
    "Generated by Kyther on {date} from <b>publicly available sources only</b>. Every "
    "finding carries a confidence level (CONFIRMED / PROBABLE / POSSIBLE); <b>POSSIBLE "
    "matches include false positives</b> and all findings must be <b>verified "
    "independently</b> before any reliance. No private, paywalled, or authenticated data "
    "was accessed. This is <b>not a background check</b> and was produced for authorized "
    "security research and portfolio demonstration. Subject identifiers are anonymized "
    "where shown."
)


# ── Page decorations: diagonal SAMPLE watermark + "Page n of N" footer ───────
class NumberedCanvas(canvas.Canvas):
    footer = "Kyther OSINT Assessment"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved = []

    def showPage(self):
        self._saved.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved)
        for state in self._saved:
            self.__dict__.update(state)
            self._decorate(total)
            super().showPage()
        super().save()

    def _decorate(self, total):
        w, h = letter
        self.saveState()  # watermark
        self.setFont("Helvetica-Bold", 96)
        self.setFillColor(colors.Color(0, 0, 0, alpha=0.05))
        self.translate(w / 2.0, h / 2.0)
        self.rotate(45)
        self.drawCentredString(0, -34, "SAMPLE")
        self.restoreState()
        self.saveState()  # footer
        self.setFont("Helvetica", 7)
        self.setFillColor(MUTED)
        self.drawString(0.85 * inch, 0.5 * inch, self.footer)
        self.drawRightString(w - 0.85 * inch, 0.5 * inch,
                             "Page %d of %d" % (self._pageNumber, total))
        self.restoreState()


# ── The Kyther wings mark, drawn as vector (no image/svglib dependency) ──────
_WINGS = [
    [("m", 382, 292), ("c", 268, 300, 158, 366, 122, 452), ("c", 165, 470, 300, 436, 398, 400)],
    [("m", 452, 300), ("c", 566, 306, 652, 372, 690, 448), ("c", 655, 470, 528, 440, 458, 404)],
    [("m", 398, 225), ("l", 398, 612)],
    [("m", 402, 392), ("l", 540, 258)],
    [("m", 406, 400), ("l", 536, 600)],
]


class WingsLogo(Flowable):
    def __init__(self, width=84):
        super().__init__()
        self.width = width
        self.height = width * 425 / 620
        self.hAlign = "CENTER"

    def wrap(self, aw, ah):
        return (self.width, self.height)

    def draw(self):
        c = self.canv
        vx0, vy0, vw, vh = 95, 205, 620, 425

        def M(x, y):
            return ((x - vx0) / vw * self.width, (1 - (y - vy0) / vh) * self.height)

        c.setStrokeColor(PURPLE_LT)
        c.setLineWidth(max(1.4, self.width * 0.028))
        c.setLineCap(1)
        c.setLineJoin(1)
        for path in _WINGS:
            p = c.beginPath()
            for seg in path:
                if seg[0] == "m":
                    p.moveTo(*M(seg[1], seg[2]))
                elif seg[0] == "l":
                    p.lineTo(*M(seg[1], seg[2]))
                else:  # cubic
                    a, b, d = M(seg[1], seg[2]), M(seg[3], seg[4]), M(seg[5], seg[6])
                    p.curveTo(a[0], a[1], b[0], b[1], d[0], d[1])
            c.drawPath(p)


# ── Report ──────────────────────────────────────────────────────────────────
class Report:
    def __init__(self, scan: dict, anonymize: bool = True):
        self.scan = scan
        self.anonymize = anonymize
        self.now = datetime.now(timezone.utc)
        self.s = self._styles()

    # -- helpers --
    def _styles(self):
        base = getSampleStyleSheet()["Normal"]

        def st(name, **kw):
            return ParagraphStyle(name, parent=base, **kw)

        return {
            "title": st("title", fontName=FONT_TITLE, fontSize=34, textColor=PURPLE,
                        alignment=TA_CENTER, leading=38, spaceAfter=2, tracking=4),
            "subtitle": st("subtitle", fontName=FONT_BODY, fontSize=12, textColor=MUTED,
                           alignment=TA_CENTER, leading=16),
            "disclaimer": st("disclaimer", fontName=FONT_BODY, fontSize=6.5, textColor=MUTED,
                             alignment=TA_CENTER, leading=9.5),
            "h2": st("h2", fontName=FONT_TITLE, fontSize=13, textColor=PURPLE,
                     spaceBefore=8, spaceAfter=9),
            "body": st("body", fontName=FONT_BODY, fontSize=9.5, textColor=INK, leading=14),
            "meta": st("meta", fontName=FONT_BODY, fontSize=10, textColor=INK, leading=14),
            "mono": st("mono", fontName=FONT_MONO, fontSize=6.5, textColor=INK, leading=8.5),
            "chip": st("chip", fontName=FONT_BODY, fontSize=8, textColor=INK, leading=15),
            "label": st("label", fontName=FONT_TITLE, fontSize=8, textColor=MUTED,
                        leading=11, spaceBefore=10, spaceAfter=6),
        }

    def _anonymize(self, value: str, type: str) -> str:
        """Redact email/phone; show username/handle (low-sensitivity, pseudonymous)."""
        if not self.anonymize or type in ("username", "person", "company"):
            return value
        if type == "email":
            local, _, dom = value.partition("@")
            tld = dom.rsplit(".", 1)[-1] if "." in dom else dom
            return f"{local[:1]}•••@•••.{tld}"
        if type == "phone":
            digits = [c for c in value if c.isdigit()]
            return "•••-•••-" + "".join(digits[-4:]) if len(digits) >= 4 else "•••"
        return (value[:1] + "•••" + value[-1:]) if len(value) > 2 else "•••"

    def _case_ref(self) -> str:
        h = hashlib.sha1(self.scan["seed"]["value"].encode()).hexdigest()[:4].upper()
        return f"KY-{self.now:%Y%m%d}-{h}"

    # -- sections (each returns a list of flowables) --
    def cover_page(self):
        seed = self.scan["seed"]
        risk = (self.scan.get("dossier") or {}).get("risk") or {"tier": "Low", "score": 0}
        subject = self._anonymize(seed["value"], seed["type"])
        ran = len({f["analyzer"] for f in self.scan.get("findings", [])})
        tier = risk.get("tier", "Low")

        els = [Spacer(1, 1.15 * inch), WingsLogo(86), Spacer(1, 0.18 * inch),
               Paragraph("KYTHER", self.s["title"]),
               Paragraph("OSINT Exposure Assessment", self.s["subtitle"]),
               Spacer(1, 0.12 * inch),
               HRFlowable(width="62%", thickness=1.1, color=PURPLE, spaceBefore=2, spaceAfter=2,
                          hAlign="CENTER"),
               Spacer(1, 0.5 * inch)]

        meta = [["Subject", f"{subject}  ({seed['type']})"],
                ["Case ref", self._case_ref()],
                ["Generated", self.now.strftime("%d %b %Y · %H:%M UTC")],
                ["Scope", f"public sources · {ran} analyzers engaged"]]
        mt = Table(meta, colWidths=[1.3 * inch, 3.9 * inch], hAlign="CENTER")
        mt.setStyle(TableStyle([
            ("FONT", (0, 0), (0, -1), FONT_BODY, 8.5),
            ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
            ("FONT", (1, 0), (1, -1), FONT_MONO, 9.5),
            ("TEXTCOLOR", (1, 0), (1, -1), INK),
            ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LINEBELOW", (0, 0), (-1, -2), 0.5, HAIRLINE),
        ]))
        els += [mt, Spacer(1, 0.5 * inch)]

        band = Table([[f"OVERALL RISK    {tier.upper()} · {risk['score']} / 100"]],
                     colWidths=[5.2 * inch], hAlign="CENTER")
        band.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), TIER_COLOR.get(tier, TIER_COLOR["Low"])),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
            ("FONT", (0, 0), (-1, -1), FONT_TITLE, 13),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 11), ("BOTTOMPADDING", (0, 0), (-1, -1), 11),
        ]))
        els += [band, Spacer(1, 1.0 * inch),
                Paragraph(DISCLAIMER.format(date=self.now.strftime("%d %b %Y")),
                          self.s["disclaimer"]),
                PageBreak()]
        return els

    # -- stubs: fill these in against the design spec --
    def _confirmed_count(self) -> int:
        return sum(1 for a in self._dedupe_accounts() if a.get("confidence") == "confirmed")

    def _breach_summary(self):
        """Returns (count, ran): count of breaches, and whether a breach source ran."""
        findings = self.scan.get("findings", [])
        hibp = [f for f in findings if f.get("category") == "breaches"]
        if hibp:
            return sum(len(f["data"].get("breaches", [])) for f in hibp), True
        er = [f for f in findings if f.get("analyzer") == "emailrep"]
        if er:
            return (1 if any(f["data"].get("data_breach") for f in er) else 0), True
        return 0, False  # no breach source configured

    def _narrative(self) -> str:
        dossier = self.scan.get("dossier") or {}
        risk = dossier.get("risk") or {}
        tier, score = risk.get("tier", "Low"), risk.get("score", 0)
        confirmed = self._confirmed_count()
        breadth = ("an extensive" if confirmed > 100 else "a moderate" if confirmed > 25
                   else "a limited" if confirmed else "no")

        drivers = [f"{breadth} confirmed account footprint ({confirmed} platform"
                   f"{'s' if confirmed != 1 else ''})"]
        if dossier.get("primary_name") and dossier.get("locations"):
            drivers.append("a real name and location linkable to the handle")
        joined = " and ".join(drivers) if len(drivers) < 3 else \
            ", ".join(drivers[:-1]) + ", and " + drivers[-1]

        parts = [f"The subject presents <b>{tier.lower()}-level public exposure</b> ({score}/100), "
                 f"driven primarily by {joined}."]
        n, ran = self._breach_summary()
        if not ran:
            parts.append("Breach exposure was not assessed, as no breach source is configured.")
        elif n:
            parts.append(f"The associated email additionally appears in {n} known data "
                         f"breach{'es' if n != 1 else ''}.")
        else:
            parts.append("No breach exposure was found for the associated email.")
        parts.append("Lower-confidence (POSSIBLE) matches are unverified and heavily "
                     "discounted in the score.")
        return " ".join(parts)

    def executive_summary(self):
        dossier = self.scan.get("dossier") or {}
        risk = dossier.get("risk") or {"tier": "Low", "score": 0, "factors": []}
        tier = risk.get("tier", "Low")
        tier_hex = _hexstr(TIER_COLOR.get(tier, TIER_COLOR["Low"]))
        confirmed = self._confirmed_count()
        n, ran = self._breach_summary()
        has_id = bool(dossier.get("primary_name") and dossier.get("locations"))
        id_val = ("Name + Location" if has_id
                  else "Name only" if dossier.get("primary_name") else "Pseudonymous")

        els = [Paragraph("Executive Summary", self.s["h2"])]

        def chip(label, value, hexcolor):
            return Paragraph(
                f'<font size="6.5" color="#6B6475">{label}</font><br/><br/>'
                f'<font size="12" color="{hexcolor}"><b>{value}</b></font>', self.s["chip"])

        chips = [[
            chip("RISK", f"{tier.upper()} · {risk['score']}/100", tier_hex),
            chip("CONFIRMED ACCOUNTS", str(confirmed), _hexstr(INK)),
            chip("IDENTITY", id_val, SEM_AMBER if has_id else SEM_GREEN),
            chip("BREACHES", ("no source" if not ran else str(n)),
                 SEM_RED if (ran and n) else "#6B6475"),
        ]]
        ct = Table(chips, colWidths=[1.5 * inch] * 4)
        ct.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#faf9fc")),
            ("LINEABOVE", (0, 0), (0, 0), 2.5, TIER_COLOR.get(tier, TIER_COLOR["Low"])),
            ("LINEABOVE", (1, 0), (1, 0), 2.5, PURPLE),
            ("LINEABOVE", (2, 0), (2, 0), 2.5,
             colors.HexColor(SEM_AMBER if has_id else SEM_GREEN)),
            ("LINEABOVE", (3, 0), (3, 0), 2.5,
             colors.HexColor(SEM_RED) if (ran and n) else HAIRLINE),
            ("INNERGRID", (0, 0), (-1, -1), 4, colors.white),  # white gutters between chips
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 9), ("BOTTOMPADDING", (0, 0), (-1, -1), 11),
            ("LEFTPADDING", (0, 0), (-1, -1), 9), ("RIGHTPADDING", (0, 0), (-1, -1), 9),
        ]))
        els.append(ct)

        # Top risk factors
        els.append(Paragraph("TOP RISK FACTORS", self.s["label"]))
        fdata = [[str(i), f["label"], f'{f["points"]}']
                 for i, f in enumerate(risk.get("factors", [])[:3], 1)]
        if fdata:
            ft = Table(fdata, colWidths=[0.3 * inch, 4.75 * inch, 0.65 * inch])
            ft.setStyle(TableStyle([
                ("FONT", (0, 0), (0, -1), FONT_TITLE, 9), ("TEXTCOLOR", (0, 0), (0, -1), PURPLE),
                ("FONT", (1, 0), (1, -1), FONT_BODY, 9.5), ("TEXTCOLOR", (1, 0), (1, -1), INK),
                ("FONT", (2, 0), (2, -1), FONT_MONO, 9), ("TEXTCOLOR", (2, 0), (2, -1), MUTED),
                ("ALIGN", (2, 0), (2, -1), "RIGHT"), ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LINEBELOW", (0, 0), (-1, -2), 0.25, HAIRLINE),
            ]))
            els.append(ft)

        # Assessment narrative
        els.append(Paragraph("ASSESSMENT", self.s["label"]))
        els.append(Paragraph(self._narrative(), self.s["body"]))
        els.append(Spacer(1, 0.12 * inch))
        return els

    MAX_ROWS_PER_GROUP = 50  # keep the report readable; low-confidence noise is capped

    def _platform_from_url(self, url: str) -> str:
        """github.com/torvalds -> 'Github'; falls back cleanly on odd URLs."""
        host = urlsplit(url if "//" in url else "//" + url).netloc.lower().split(":")[0]
        labels = [l for l in host.split(".") if l]
        label = labels[-2] if len(labels) >= 2 else (labels[0] if labels else host)
        return label.capitalize() or host

    def _dedupe_accounts(self):
        """One row per host, keeping the highest-confidence source when duplicated."""
        best: dict[str, dict] = {}
        for f in self.scan.get("findings", []):
            if f.get("category") != "accounts":
                continue
            for p in f.get("data", {}).get("profiles", []):
                host = urlsplit(p["url"]).netloc.replace("www.", "").lower() or p["url"]
                conf = p.get("confidence", "possible")
                cur = best.get(host)
                if cur is None or CONF_RANK.get(conf, 0) > CONF_RANK.get(cur.get("confidence", "possible"), 0):
                    best[host] = {**p, "confidence": conf}
        return list(best.values())

    def findings_accounts(self):
        accounts = self._dedupe_accounts()
        els = [Paragraph("Findings · Accounts", self.s["h2"])]
        if not accounts:
            els.append(Paragraph("No accounts found.", self.s["body"]))
            return els

        sources = sum(1 for f in self.scan.get("findings", []) if f.get("category") == "accounts")
        els.append(Paragraph(
            f"{len(accounts)} unique accounts across {sources} source(s), grouped by "
            "confidence. Weight is each account's contribution to the footprint factor.",
            self.s["body"]))

        groups = {c: [] for c in CONF_ORDER}
        for a in accounts:
            groups.setdefault(a.get("confidence", "possible"), []).append(a)

        for level in CONF_ORDER:
            rows = sorted(groups[level], key=lambda a: (a.get("platform") or "").lower())
            if not rows:
                continue
            fill, text, glyph = CONF_STYLE[level]
            shown = rows[: self.MAX_ROWS_PER_GROUP]

            els.append(Spacer(1, 0.14 * inch))
            gh = ParagraphStyle("gh", parent=self.s["body"], fontName=FONT_TITLE,
                                fontSize=10, textColor=text, spaceAfter=4)
            els.append(Paragraph(f"{glyph} {level.upper()} ({len(rows)}) — {CONF_DESC[level]}", gh))

            data = [["Platform", "URL", "Weight"]]
            for a in shown:
                plat = a.get("platform") or self._platform_from_url(a["url"])
                url = a["url"].split("//", 1)[-1].replace("www.", "")
                if len(url) > 52:
                    url = url[:51] + "…"
                data.append([plat, url, CONF_WEIGHT.get(a.get("confidence"), "")])

            t = Table(data, colWidths=[1.55 * inch, 3.95 * inch, 0.65 * inch], repeatRows=1)
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), fill),          # header row = confidence tint
                ("TEXTCOLOR", (0, 0), (-1, 0), text),
                ("FONT", (0, 0), (-1, 0), FONT_TITLE, 7.5),
                ("LINEBELOW", (0, 0), (-1, 0), 0.7, text),
                ("FONT", (0, 1), (0, -1), FONT_BODY, 8.5),       # platform
                ("TEXTCOLOR", (0, 1), (0, -1), INK),
                ("FONT", (1, 1), (1, -1), FONT_MONO, 7.5),       # url
                ("TEXTCOLOR", (1, 1), (1, -1), MUTED),
                ("FONT", (2, 1), (2, -1), FONT_MONO, 8),         # weight
                ("TEXTCOLOR", (2, 1), (2, -1), text),
                ("ALIGN", (2, 0), (2, -1), "RIGHT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#faf9fc")]),
                ("LINEBELOW", (0, 1), (-1, -2), 0.25, HAIRLINE),
                ("TOPPADDING", (0, 0), (-1, -1), 3.5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
            ]))
            els.append(t)
            if len(rows) > len(shown):
                els.append(Paragraph(
                    f"… and {len(rows) - len(shown)} more {level} accounts (omitted for brevity).",
                    ParagraphStyle("note", parent=self.s["body"], fontSize=7.5,
                                   textColor=MUTED, spaceBefore=3)))
        return els

    def _badge(self, level: str):
        """Color-coded confidence pill for a table cell."""
        _, text, glyph = CONF_STYLE.get(level, CONF_STYLE["possible"])
        return Paragraph(f'<font color="{_hexstr(text)}"><b>{glyph} {level.upper()}</b></font>',
                         ParagraphStyle("badge", parent=self.s["body"], fontSize=7.5, leading=10))

    def _other_findings(self):
        """Rows of (type, detail, source, confidence) for identity/contact findings."""
        d = self.scan.get("dossier") or {}
        rows = []
        for e in d.get("emails", []):
            raw = e.get("source")
            src = {"seed": "Search input", "hunter": "Hunter.io",
                   None: "GitHub commits"}.get(raw, raw or "GitHub commits")
            level = "probable" if raw == "hunter" else "confirmed"
            detail = self._anonymize(e["email"], "email") + (" (noreply)" if e.get("noreply") else "")
            rows.append(("Email", detail, src, level))
        if d.get("primary_name"):
            rows.append(("Name", d["primary_name"], "Profile enrichment", "confirmed"))
        for loc in (d.get("locations") or [])[:2]:
            rows.append(("Location", loc, "Profile enrichment", "confirmed"))
        for co in (d.get("companies") or [])[:2]:
            rows.append(("Employer", co, "Profile enrichment", "confirmed"))
        for f in self.scan.get("findings", []):
            if f.get("analyzer") == "phone_intel":
                pd = f.get("data", {})
                detail = self._anonymize(pd.get("e164") or self.scan["seed"]["value"], "phone")
                extra = " · ".join(x for x in (pd.get("location"), pd.get("line_type")) if x)
                rows.append(("Phone", f"{detail} ({extra})" if extra else detail,
                             "libphonenumber", "confirmed"))
        return rows

    def findings_other(self):
        rows = self._other_findings()
        els = [Paragraph("Findings · Identity &amp; Contact", self.s["h2"])]
        if not rows:
            els.append(Paragraph("No identity or contact findings.", self.s["body"]))
            return els

        data = [["Type", "Detail", "Source", "Confidence"]]
        for typ, detail, src, level in rows:
            data.append([typ, detail, src, self._badge(level)])
        t = Table(data, colWidths=[0.85 * inch, 3.0 * inch, 1.35 * inch, 1.15 * inch], repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f2eef7")),  # purple-tint header
            ("TEXTCOLOR", (0, 0), (-1, 0), PURPLE),
            ("FONT", (0, 0), (-1, 0), FONT_TITLE, 7.5),
            ("LINEBELOW", (0, 0), (-1, 0), 0.7, PURPLE),
            ("FONT", (0, 1), (0, -1), FONT_BODY, 8.5), ("TEXTCOLOR", (0, 1), (0, -1), INK),
            ("FONT", (1, 1), (1, -1), FONT_MONO, 7.5), ("TEXTCOLOR", (1, 1), (1, -1), INK),
            ("FONT", (2, 1), (2, -1), FONT_MONO, 7.5), ("TEXTCOLOR", (2, 1), (2, -1), MUTED),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#faf9fc")]),
            ("LINEBELOW", (0, 1), (-1, -2), 0.25, HAIRLINE),
            ("TOPPADDING", (0, 0), (-1, -1), 3.5), ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
            ("LEFTPADDING", (0, 0), (-1, -1), 7), ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ]))
        els += [t, Spacer(1, 0.14 * inch)]
        return els

    def methodology(self):
        ran = sorted({f["analyzer"] for f in self.scan.get("findings", [])})
        items = [
            ("Orchestration", "The seed entity is dispatched to up to 18 analyzers that run "
             "concurrently; entities they discover (emails, domains, handles) pivot back in, "
             "depth-limited, and all findings are aggregated and de-duplicated."),
            ("Sources", "Public, no-authentication data only — no paywalled, private, or "
             "authenticated sources are accessed."),
            ("Confidence", "<b>CONFIRMED</b> = authoritative (control-verified match or "
             "structured API data); <b>PROBABLE</b> = a strong corroborating signal; "
             "<b>POSSIBLE</b> = an HTTP-status-code-only match, which includes false positives."),
            ("Risk model", "Score = Σ(sensitivity × confidence) + 5·ln(1 + effective_accounts) "
             "+ confidence-scaled bonuses, clamped to 0–100. Effective accounts weight each "
             "match by its confidence (×1.0 / ×0.6 / ×0.2)."),
            ("Limitations", "POSSIBLE matches are unverified and must be checked manually; "
             "breach assessment requires a keyed source; rate-limited enrichment can reduce "
             "coverage between runs, so scores reflect the data available at scan time; all "
             "scores are advisory and not a background check."),
        ]
        els = [PageBreak(), Paragraph("Methodology", self.s["h2"])]
        for label, text in items:
            els.append(Paragraph(f"<b>{label}.</b> {text}", self.s["body"]))
            els.append(Spacer(1, 0.06 * inch))
        els.append(Paragraph("ANALYZERS ENGAGED THIS SCAN", self.s["label"]))
        els.append(Paragraph(
            ", ".join(ran) if ran else "none",
            ParagraphStyle("ana", parent=self.s["body"], fontName=FONT_MONO, fontSize=8,
                           textColor=INK, leading=13)))
        return els

    @staticmethod
    def _redact_scalar(s: str) -> str:
        if _EMAIL_RE.match(s):
            return "***@***.***"
        if _URL_RE.match(s):
            return "***"
        digits = re.sub(r"\D", "", s)
        if s.strip().startswith("+") and len(digits) >= 7:  # E.164-ish phone
            return "***"
        return s

    def _redact_json(self, obj):
        """Deep copy with email / URL / phone values masked; usernames & names kept
        (same policy as _anonymize)."""
        if isinstance(obj, dict):
            return {k: self._redact_json(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [self._redact_json(v) for v in obj]
        if isinstance(obj, str):
            return self._redact_scalar(obj)
        return obj

    def appendix(self):
        data = self._redact_json(self.scan) if self.anonymize else self.scan
        raw = json.dumps(data, indent=2, ensure_ascii=False)
        truncated = len(raw) > 8000
        if truncated:
            raw = raw[:8000].rstrip() + "\n… (output truncated)"
        # wrap long lines (Preformatted preserves whitespace but does not wrap)
        raw = "\n".join(
            "\n".join(textwrap.wrap(ln, width=112, subsequent_indent="    ",
                                    break_long_words=True, break_on_hyphens=False))
            if len(ln) > 112 else ln
            for ln in raw.splitlines())
        raw = raw.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

        code = ParagraphStyle("code", parent=self.s["mono"], fontSize=6.5, leading=8.5,
                              textColor=MUTED)
        els = [PageBreak(), Paragraph("APPENDIX A · RAW SCAN DATA", self.s["h2"])]
        if self.anonymize:
            els.append(Paragraph("Email, phone, and URL values are redacted; usernames and "
                                 "display names are retained (consistent with the cover).",
                                 self.s["body"]))
        if truncated:
            els.append(Paragraph("Output capped at 8,000 characters.",
                                 ParagraphStyle("note", parent=self.s["body"], fontSize=7.5,
                                                textColor=MUTED)))
        els += [Spacer(1, 0.08 * inch), Preformatted(raw, code)]
        return els

    # -- assembly --
    def generate(self) -> bytes:
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=letter, title="Kyther OSINT Assessment",
            leftMargin=0.85 * inch, rightMargin=0.85 * inch,
            topMargin=0.8 * inch, bottomMargin=0.85 * inch,
        )
        NumberedCanvas.footer = "Kyther OSINT Assessment · " + self.now.strftime("%d %b %Y")
        story = (self.cover_page() + self.executive_summary() + self.findings_accounts()
                 + self.findings_other() + self.methodology() + self.appendix())
        doc.build(story, canvasmaker=NumberedCanvas)
        return buf.getvalue()
